#!/bin/bash

gcc main.c -L./libft -lft

if [ "$1" = -v ];
then
	echo "**START WITH VALGRIND CONTROL"
	valgrind --leak-check=full \
			--show-leak-kinds=all \
			--track-origins=yes \
			--verbose \
			--verbose \
			--log-file=./extra/valgrind-out.txt \
			-s ./a.out "./map.cub"  && rm ./a.out
	cat ./extra/valgrind-out.txt
else
	./a.out "./map.cub" && rm ./a.out
fi